modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"
issueTrackerURL = "${issues}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = "${description}"
logoFile = "assets/${id}/icon.png"
authors = ["lupiiin_", "lowercasebtw", "luavixen <lua@foxgirl.dev> (https://foxgirl.dev/)"]
displayURL = "${modrinth}"

[[mixins]]
config = "${id}.mixins.json"

[[dependencies.${id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"
